Repository Automattic/VIP-Coding-Standards, pull requests merged in 2018-08, with the labels that each got.

#195 Silence the .com user meta function sniffs for VIP Go
  WordPress-VIP-Go/ruleset.xml
  WordPressVIPMinimum/Tests/VIP/RestrictedFunctionsUnitTest.php
  ruleset_test.php
Labels: bug

#192 changed the html string concatenation message
  WordPressVIPMinimum/Sniffs/JS/StringConcatSniff.php
Labels: enhancement

#202 PHPCS fixes
  WordPressVIPMinimum/Sniffs/Actions/PreGetPostsSniff.php
  WordPressVIPMinimum/Sniffs/Cache/BatcacheWhitelistedParamsSniff.php
  WordPressVIPMinimum/Sniffs/Cache/CacheValueOverrideSniff.php
  WordPressVIPMinimum/Sniffs/Classes/DeclarationCompatibilitySniff.php
  WordPressVIPMinimum/Sniffs/Constants/ConstantRestrictionsSniff.php
  WordPressVIPMinimum/Sniffs/Constants/ConstantStringSniff.php
  WordPressVIPMinimum/Sniffs/Files/IncludingFileSniff.php
  WordPressVIPMinimum/Sniffs/Files/IncludingNonPHPFileSniff.php
  WordPressVIPMinimum/Sniffs/Functions/CheckReturnValueSniff.php
  WordPressVIPMinimum/Sniffs/Functions/DynamicCallsSniff.php
  WordPressVIPMinimum/Sniffs/JS/HTMLExecutingFunctionsSniff.php
  WordPressVIPMinimum/Sniffs/JS/InnerHTMLSniff.php
  WordPressVIPMinimum/Sniffs/JS/StringConcatSniff.php
  WordPressVIPMinimum/Sniffs/JS/StrippingTagsSniff.php
  WordPressVIPMinimum/Sniffs/Plugins/ZoninatorSniff.php
  WordPressVIPMinimum/Sniffs/TemplatingEngines/UnescapedOutputMustacheSniff.php
  WordPressVIPMinimum/Sniffs/TemplatingEngines/UnescapedOutputTwigSniff.php
  WordPressVIPMinimum/Sniffs/TemplatingEngines/UnescapedOutputUnderscorejsSniff.php
  WordPressVIPMinimum/Sniffs/TemplatingEngines/UnescapedOutputVuejsSniff.php
  WordPressVIPMinimum/Sniffs/VIP/ExitAfterRedirectSniff.php
  WordPressVIPMinimum/Sniffs/VIP/ProperEscapingFunctionSniff.php
  WordPressVIPMinimum/Sniffs/VIP/RegexpCompareSniff.php
  WordPressVIPMinimum/Sniffs/VIP/RemoteRequestTimeoutSniff.php
  WordPressVIPMinimum/Sniffs/VIP/RestrictedFunctionsSniff.php
  WordPressVIPMinimum/Sniffs/VIP/StaticStrreplaceSniff.php
  WordPressVIPMinimum/Sniffs/VIP/TaxonomyMetaInOptionsSniff.php
  WordPressVIPMinimum/Sniffs/Variables/ServerVariablesSniff.php
  WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisHelper.php
  WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisSniff.php
  ruleset_test.php
Labels: enhancement

#203 fixes some regressions with WPCS 1 support
  WordPress-VIP-Go/ruleset.xml
Labels: bug

#177 Add filters always return sniff
  WordPressVIPMinimum/Sniffs/Filters/AlwaysReturnSniff.php
  WordPressVIPMinimum/Tests/Filters/AlwaysReturnUnitTest.inc
  WordPressVIPMinimum/Tests/Filters/AlwaysReturnUnitTest.php
Labels: enhancement, help wanted

#204 Fix error of WordPress.WP.GlobalVariables.OverrideProhibited not existing
  WordPress-VIP-Go/ruleset.xml
Labels: New VIP Go Standards, bug

#158 Sniff to detect create_function()
  WordPressVIPMinimum/Sniffs/Functions/CreateFunctionSniff.php
  WordPressVIPMinimum/Tests/Functions/CreateFunctionSniff.inc
  WordPressVIPMinimum/Tests/Functions/CreateFunctionSniff.php
Labels: enhancement, help wanted

#185 Add coding standards checks to VIP CS
  .phpcs.xml.dist
  .travis.yml
  WordPress-VIP-Go/ruleset.xml
  WordPressVIPMinimum/Sniffs/Filters/AlwaysReturnSniff.php
  WordPressVIPMinimum/Sniffs/Functions/CheckReturnValueSniff.php
  WordPressVIPMinimum/Sniffs/Functions/CreateFunctionSniff.php
  WordPressVIPMinimum/Sniffs/Functions/DynamicCallsSniff.php
  WordPressVIPMinimum/Sniffs/VIP/MergeConflictSniff.php
  WordPressVIPMinimum/Sniffs/VIP/RobotstxtSniff.php
  WordPressVIPMinimum/Tests/Actions/PreGetPostsUnitTest.php
  WordPressVIPMinimum/Tests/Cache/BatcacheWhitelistedParamsUnitTest.php
  WordPressVIPMinimum/Tests/Cache/CacheValueOverrideUnitTest.php
  WordPressVIPMinimum/Tests/Classes/DeclarationCompatibilityUnitTest.php
  WordPressVIPMinimum/Tests/Constants/ConstantRestrictionsUnitTest.php
  WordPressVIPMinimum/Tests/Constants/ConstantStringUnitTest.php
  WordPressVIPMinimum/Tests/Files/IncludingFileUnitTest.php
  WordPressVIPMinimum/Tests/Files/IncludingNonPHPFileUnitTest.php
  WordPressVIPMinimum/Tests/Filters/AlwaysReturnUnitTest.php
  WordPressVIPMinimum/Tests/Functions/CheckReturnValueUnitTest.php
  WordPressVIPMinimum/Tests/Functions/CreateFunctionSniff.php
  WordPressVIPMinimum/Tests/Functions/DynamicCallsUnitTest.php
  WordPressVIPMinimum/Tests/JS/HTMLExecutingFunctionsUnitTest.php
  WordPressVIPMinimum/Tests/JS/InnerHTMLUnitTest.php
  WordPressVIPMinimum/Tests/JS/StringConcatUnitTest.php
  WordPressVIPMinimum/Tests/JS/StrippingTagsUnitTest.php
  WordPressVIPMinimum/Tests/Plugins/ZoninatorUnitTest.php
  WordPressVIPMinimum/Tests/TemplatingEngines/UnescapedOutputMustacheUnitTest.php
  WordPressVIPMinimum/Tests/TemplatingEngines/UnescapedOutputTwigUnitTest.php
  WordPressVIPMinimum/Tests/TemplatingEngines/UnescapedOutputUnderscorejsUnitTest.php
  WordPressVIPMinimum/Tests/TemplatingEngines/UnescapedOutputVuejsUnitTest.php
  WordPressVIPMinimum/Tests/VIP/ErrorControlUnitTest.php
  WordPressVIPMinimum/Tests/VIP/EscapingVoidReturnFunctionsUnitTest.php
  WordPressVIPMinimum/Tests/VIP/ExitAfterRedirectUnitTest.php
  WordPressVIPMinimum/Tests/VIP/FetchingRemoteDataUnitTest.php
  WordPressVIPMinimum/Tests/VIP/FlushRewriteRulesUnitTest.php
  WordPressVIPMinimum/Tests/VIP/MergeConflictUnitTest.php
  WordPressVIPMinimum/Tests/VIP/ProperEscapingFunctionUnitTest.php
  WordPressVIPMinimum/Tests/VIP/RegexpCompareUnitTest.php
  WordPressVIPMinimum/Tests/VIP/RemoteRequestTimeoutUnitTest.php
  WordPressVIPMinimum/Tests/VIP/RestrictedFunctionsUnitTest.php
  WordPressVIPMinimum/Tests/VIP/StaticStrreplaceUnitTest.php
  WordPressVIPMinimum/Tests/VIP/TaxonomyMetaInOptionsUnitTest.php
  WordPressVIPMinimum/Tests/VIP/WPQueryParamsUnitTest.php
  WordPressVIPMinimum/Tests/Variables/ServerVariablesUnitTest.php
  WordPressVIPMinimum/Tests/Variables/VariableAnalysisUnitTest.php
  bin/phpcs.xml
  composer.json
Labels: enhancement, help wanted
