Repository Automattic/VIP-Coding-Standards, pull requests merged in 2018-12, with the labels that each got.

#291 Fix AlwaysReturnSniff for missing return statement
  WordPressVIPMinimum/Sniffs/Filters/AlwaysReturnSniff.php
  WordPressVIPMinimum/Tests/Filters/AlwaysReturnUnitTest.inc
  WordPressVIPMinimum/Tests/Filters/AlwaysReturnUnitTest.php
Labels: Standard: VIPMinimum, Status: Awaiting feedback

#292 Add PHP Syntax Error sniff to WordPressVIPMinimum
  WordPressVIPMinimum/ruleset.xml
  ruleset_test.inc
  ruleset_test.php
Labels: Priority: High, Standard: VIPMinimum, Status: Awaiting feedback

#297 Docs: Updates Readme notes
  README.md
Labels: Type: Documentation

#295 Fix PHPCS violations in VIPCS
  WordPressVIPMinimum/Sniffs/Classes/RestrictedExtendClassesSniff.php
  WordPressVIPMinimum/Sniffs/Filters/RestrictedHookSniff.php
  WordPressVIPMinimum/Sniffs/Functions/StripTagsSniff.php
  WordPressVIPMinimum/Sniffs/JS/WindowSniff.php
  WordPressVIPMinimum/Sniffs/Variables/ServerVariablesSniff.php
  WordPressVIPMinimum/Tests/Filters/AlwaysReturnUnitTest.php
  WordPressVIPMinimum/Tests/Filters/RestrictedHookUnitTest.php
  WordPressVIPMinimum/Tests/Variables/VariableAnalysisUnitTest.php
  bin/phpcs
Labels: Type: Chore

#296 Change Composer test script order
  composer.json
Labels: Type: Enhancement

#288 Add change log (starting at 0.4.0)
  CHANGELOG.md
Labels: Type: Documentation

#306 PHPCS: Bump testVersion to match PHP requirement
  .phpcs.xml.dist
Labels: Type: Bug

#303 Use PHPCS 3.x namespaced classes
  WordPressVIPMinimum/Sniffs/Filters/AlwaysReturnSniff.php
  WordPressVIPMinimum/Sniffs/Functions/CreateFunctionSniff.php
  WordPressVIPMinimum/Sniffs/VIP/MergeConflictSniff.php
  WordPressVIPMinimum/Sniffs/VIP/RobotstxtSniff.php
Labels: Type: Chore

#307 FetchingRemoteDataSniff: Fix typo of missing "n" in "Unknown".
  WordPressVIPMinimum/Sniffs/VIP/FetchingRemoteDataSniff.php
Labels: Type: Bug

#308 PHPCS: Add XSD reference and validate rulesets
  .phpcs.xml.dist
  .travis.yml
  WordPress-VIP-Go/ruleset.xml
  WordPressVIPMinimum/ruleset.xml
  bin/xml-lint
Labels: Type: Enhancement

#310 AlwaysReturnSniff will trigger errors unless callback args is pass by reference
  WordPressVIPMinimum/Sniffs/Filters/AlwaysReturnSniff.php
  WordPressVIPMinimum/Tests/Filters/AlwaysReturnUnitTest.inc
  WordPressVIPMinimum/Tests/Filters/AlwaysReturnUnitTest.php
Labels: Type: Enhancement

#316 Switch to phpcodesniffer-composer-installer v0.5.0
  composer.json
Labels: Type: Chore

#318 Use phpcodesniffer-composer-installer plugin
  composer.json
Labels: Type: Enhancement

#321 Travis: Add PHP 7.3 testing
  .travis.yml
Labels: Type: Chore
