Repository Automattic/VIP-Coding-Standards, pull requests merged in 2019-02, with the labels that each got.

#366 Travis: Restrict PHPUnit versions to match PHPCS
  composer.json
Labels: Type: Maintenance

#365 Re-organize WordPress-VIP-Go ruleset for consistency
  WordPress-VIP-Go/ruleset.xml
Labels: Type: Maintenance

#367 Added integration tests for WordPress-VIP-Go ruleset
  WordPress-VIP-Go/ruleset-test.inc
  WordPress-VIP-Go/ruleset-test.php
  WordPress-VIP-Go/ruleset.xml
  WordPressVIPMinimum/ruleset-test.inc
  WordPressVIPMinimum/ruleset-test.php
  bin/integration-test
Labels: Type: Maintenance

#371 Ruleset Tests Improvements
  .travis.yml
  WordPress-VIP-Go/ruleset-test.php
  WordPressVIPMinimum/ruleset-test.php
  bin/integration-test
  bin/ruleset-tests
  composer.json
  tests/RulesetTest.php
Labels: Type: Maintenance

#377 Refactor to use VIPCSSniff which is child of WordPress\Sniff
  WordPressVIPMinimum/Sniffs/AbstractVariableRestrictionsSniff.php
  WordPressVIPMinimum/Sniffs/Compatibility/ZoninatorSniff.php
  WordPressVIPMinimum/Sniffs/Constants/ConstantStringSniff.php
  WordPressVIPMinimum/Sniffs/Constants/RestrictedConstantsSniff.php
  WordPressVIPMinimum/Sniffs/Files/IncludingFileSniff.php
  WordPressVIPMinimum/Sniffs/Files/IncludingNonPHPFileSniff.php
  WordPressVIPMinimum/Sniffs/Functions/CheckReturnValueSniff.php
  WordPressVIPMinimum/Sniffs/Functions/DynamicCallsSniff.php
  WordPressVIPMinimum/Sniffs/Hooks/AlwaysReturnInFilterSniff.php
  WordPressVIPMinimum/Sniffs/Hooks/PreGetPostsSniff.php
  WordPressVIPMinimum/Sniffs/JS/DangerouslySetInnerHTMLSniff.php
  WordPressVIPMinimum/Sniffs/JS/HTMLExecutingFunctionsSniff.php
  WordPressVIPMinimum/Sniffs/JS/InnerHTMLSniff.php
  WordPressVIPMinimum/Sniffs/JS/StringConcatSniff.php
  WordPressVIPMinimum/Sniffs/JS/StrippingTagsSniff.php
  WordPressVIPMinimum/Sniffs/JS/WindowSniff.php
  WordPressVIPMinimum/Sniffs/Performance/BatcacheWhitelistedParamsSniff.php
  WordPressVIPMinimum/Sniffs/Performance/CacheValueOverrideSniff.php
  WordPressVIPMinimum/Sniffs/Performance/FetchingRemoteDataSniff.php
  WordPressVIPMinimum/Sniffs/Performance/TaxonomyMetaInOptionsSniff.php
  WordPressVIPMinimum/Sniffs/Performance/WPQueryParamsSniff.php
  WordPressVIPMinimum/Sniffs/Security/EscapingVoidReturnFunctionsSniff.php
  WordPressVIPMinimum/Sniffs/Security/ExitAfterRedirectSniff.php
  WordPressVIPMinimum/Sniffs/Security/MustacheSniff.php
  WordPressVIPMinimum/Sniffs/Security/ProperEscapingFunctionSniff.php
  WordPressVIPMinimum/Sniffs/Security/StaticStrreplaceSniff.php
  WordPressVIPMinimum/Sniffs/Security/TwigSniff.php
  WordPressVIPMinimum/Sniffs/Security/UnderscorejsSniff.php
  WordPressVIPMinimum/Sniffs/Security/VuejsSniff.php
  WordPressVIPMinimum/Sniffs/Sniff.php
  WordPressVIPMinimum/Sniffs/Variables/ServerVariablesSniff.php
  WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisSniff.php
  WordPressVIPMinimum/Sniffs/VersionControl/MergeConflictSniff.php
Labels: Type: Enhancement

#380 Docs: Add notes about Ruleset Tests
  CHANGELOG.md
  CONTRIBUTING.md
Labels: Type: Documentation

#383 Travis improvements
  .travis.yml
Labels: Type: Maintenance

#385 GH: Fix typo in enhancement template
  .github/ISSUE_TEMPLATE/enhancement.md
Labels: Type: Maintenance
