Repository Automattic/VIP-Coding-Standards, pull requests merged in 2019-01, with the labels that each got.

#286 Remove FlushRewriteRuleSniff since it is already being checked in another sniff.
  WordPressVIPMinimum/Sniffs/VIP/FlushRewriteRulesSniff.php
  WordPressVIPMinimum/Sniffs/VIP/RestrictedFunctionsSniff.php
  WordPressVIPMinimum/Tests/VIP/FlushRewriteRulesUnitTest.inc
  WordPressVIPMinimum/Tests/VIP/FlushRewriteRulesUnitTest.php
  WordPressVIPMinimum/Tests/VIP/RestrictedFunctionsUnitTest.inc
  WordPressVIPMinimum/Tests/VIP/RestrictedFunctionsUnitTest.php
Labels: Status: Need refresh, Type: Chore

#327 Copy AbstractVariableRestrictionsSniff from WPCS
  WordPressVIPMinimum/Sniffs/AbstractVariableRestrictionsSniff.php
  WordPressVIPMinimum/Sniffs/VIP/RestrictedVariablesSniff.php
Labels: Type: Chore

#326 Remove CronInterval in favour of custom property
  WordPressVIPMinimum/Sniffs/VIP/CronIntervalSniff.php
  WordPressVIPMinimum/Tests/VIP/CronIntervalUnitTest.inc
  WordPressVIPMinimum/Tests/VIP/CronIntervalUnitTest.php
  WordPressVIPMinimum/ruleset.xml
  ruleset_test.inc
  ruleset_test.php
Labels: Type: Chore

#328 Combine SessionFunctionsSniff into RestrictedFunctionsSniff and SessionVariableSniff into RestrictedVariablesSniff
  WordPressVIPMinimum/Sniffs/VIP/RestrictedFunctionsSniff.php
  WordPressVIPMinimum/Sniffs/VIP/RestrictedVariablesSniff.php
  WordPressVIPMinimum/Sniffs/VIP/SessionFunctionsUsageSniff.php
  WordPressVIPMinimum/Sniffs/VIP/SessionVariableUsageSniff.php
  WordPressVIPMinimum/Tests/VIP/RestrictedFunctionsUnitTest.inc
  WordPressVIPMinimum/Tests/VIP/RestrictedFunctionsUnitTest.php
  WordPressVIPMinimum/Tests/VIP/RestrictedVariablesUnitTest.inc
  WordPressVIPMinimum/Tests/VIP/RestrictedVariablesUnitTest.php
  WordPressVIPMinimum/Tests/VIP/SessionFunctionsUsageUnitTest.inc
  WordPressVIPMinimum/Tests/VIP/SessionFunctionsUsageUnitTest.php
  WordPressVIPMinimum/Tests/VIP/SessionVariableUsageUnitTest.inc
  WordPressVIPMinimum/Tests/VIP/SessionVariableUsageUnitTest.php
Labels: Type: Chore

#332 Replace ErrorControlSniff with upstream sniff
  WordPress-VIP-Go/ruleset.xml
  WordPressVIPMinimum/Sniffs/VIP/ErrorControlSniff.php
  WordPressVIPMinimum/Tests/VIP/ErrorControlUnitTest.inc
  WordPressVIPMinimum/Tests/VIP/ErrorControlUnitTest.php
  WordPressVIPMinimum/ruleset.xml
  ruleset_test.inc
Labels: Type: Maintenance

#337 Improve addError() and addWarning() calls
  WordPressVIPMinimum/Sniffs/Actions/PreGetPostsSniff.php
  WordPressVIPMinimum/Sniffs/Cache/BatcacheWhitelistedParamsSniff.php
  WordPressVIPMinimum/Sniffs/Cache/CacheValueOverrideSniff.php
  WordPressVIPMinimum/Sniffs/Cache/LowExpiryCacheTimeSniff.php
  WordPressVIPMinimum/Sniffs/Classes/DeclarationCompatibilitySniff.php
  WordPressVIPMinimum/Sniffs/Constants/ConstantRestrictionsSniff.php
  WordPressVIPMinimum/Sniffs/Constants/ConstantStringSniff.php
  WordPressVIPMinimum/Sniffs/Files/IncludingFileSniff.php
  WordPressVIPMinimum/Sniffs/Files/IncludingNonPHPFileSniff.php
  WordPressVIPMinimum/Sniffs/Filters/AlwaysReturnSniff.php
  WordPressVIPMinimum/Sniffs/Functions/CheckReturnValueSniff.php
  WordPressVIPMinimum/Sniffs/Functions/CreateFunctionSniff.php
  WordPressVIPMinimum/Sniffs/Functions/DynamicCallsSniff.php
  WordPressVIPMinimum/Sniffs/Functions/StripTagsSniff.php
  WordPressVIPMinimum/Sniffs/JS/DangerouslySetInnerHTMLSniff.php
  WordPressVIPMinimum/Sniffs/JS/HTMLExecutingFunctionsSniff.php
  WordPressVIPMinimum/Sniffs/JS/InnerHTMLSniff.php
  WordPressVIPMinimum/Sniffs/JS/StringConcatSniff.php
  WordPressVIPMinimum/Sniffs/JS/StrippingTagsSniff.php
  WordPressVIPMinimum/Sniffs/JS/WindowSniff.php
  WordPressVIPMinimum/Sniffs/Plugins/ZoninatorSniff.php
  WordPressVIPMinimum/Sniffs/TemplatingEngines/UnescapedOutputMustacheSniff.php
  WordPressVIPMinimum/Sniffs/TemplatingEngines/UnescapedOutputTwigSniff.php
  WordPressVIPMinimum/Sniffs/TemplatingEngines/UnescapedOutputUnderscorejsSniff.php
  WordPressVIPMinimum/Sniffs/TemplatingEngines/UnescapedOutputVuejsSniff.php
  WordPressVIPMinimum/Sniffs/VIP/AdminBarRemovalSniff.php
  WordPressVIPMinimum/Sniffs/VIP/EscapingVoidReturnFunctionsSniff.php
  WordPressVIPMinimum/Sniffs/VIP/ExitAfterRedirectSniff.php
  WordPressVIPMinimum/Sniffs/VIP/FetchingRemoteDataSniff.php
  WordPressVIPMinimum/Sniffs/VIP/MergeConflictSniff.php
  WordPressVIPMinimum/Sniffs/VIP/PHPFilterFunctionsSniff.php
  WordPressVIPMinimum/Sniffs/VIP/ProperEscapingFunctionSniff.php
  WordPressVIPMinimum/Sniffs/VIP/RemoteRequestTimeoutSniff.php
  WordPressVIPMinimum/Sniffs/VIP/RestrictedFunctionsSniff.php
  WordPressVIPMinimum/Sniffs/VIP/RobotstxtSniff.php
  WordPressVIPMinimum/Sniffs/VIP/StaticStrreplaceSniff.php
  WordPressVIPMinimum/Sniffs/VIP/TaxonomyMetaInOptionsSniff.php
  WordPressVIPMinimum/Sniffs/VIP/WPQueryParamsSniff.php
  WordPressVIPMinimum/Sniffs/Variables/ServerVariablesSniff.php
  WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisSniff.php
Labels: Type: Maintenance

#335 Update WordPress-VIP-Go ruleset file
  WordPress-VIP-Go/ruleset.xml
Labels: Type: Maintenance

#341 Move FileSystemWritesDisallowSniff into RestrictedFunctionsSniff
  WordPress-VIP-Go/ruleset.xml
  WordPressVIPMinimum/Sniffs/VIP/FileSystemWritesDisallowSniff.php
  WordPressVIPMinimum/Sniffs/VIP/RestrictedFunctionsSniff.php
  WordPressVIPMinimum/Tests/VIP/FileSystemWritesDisallowUnitTest.inc
  WordPressVIPMinimum/Tests/VIP/FileSystemWritesDisallowUnitTest.php
  WordPressVIPMinimum/Tests/VIP/RestrictedFunctionsUnitTest.inc
  WordPressVIPMinimum/Tests/VIP/RestrictedFunctionsUnitTest.php
Labels: Type: Maintenance

#342 Docs: Tidy reference to PHP_CodeSniffer/Files/File, and other docs items
  WordPressVIPMinimum/Sniffs/Actions/PreGetPostsSniff.php
  WordPressVIPMinimum/Sniffs/Cache/BatcacheWhitelistedParamsSniff.php
  WordPressVIPMinimum/Sniffs/Cache/CacheValueOverrideSniff.php
  WordPressVIPMinimum/Sniffs/Classes/DeclarationCompatibilitySniff.php
  WordPressVIPMinimum/Sniffs/Constants/ConstantRestrictionsSniff.php
  WordPressVIPMinimum/Sniffs/Constants/ConstantStringSniff.php
  WordPressVIPMinimum/Sniffs/Files/IncludingNonPHPFileSniff.php
  WordPressVIPMinimum/Sniffs/Filters/AlwaysReturnSniff.php
  WordPressVIPMinimum/Sniffs/Functions/CheckReturnValueSniff.php
  WordPressVIPMinimum/Sniffs/Functions/CreateFunctionSniff.php
  WordPressVIPMinimum/Sniffs/Functions/DynamicCallsSniff.php
  WordPressVIPMinimum/Sniffs/JS/DangerouslySetInnerHTMLSniff.php
  WordPressVIPMinimum/Sniffs/JS/HTMLExecutingFunctionsSniff.php
  WordPressVIPMinimum/Sniffs/JS/InnerHTMLSniff.php
  WordPressVIPMinimum/Sniffs/JS/StringConcatSniff.php
  WordPressVIPMinimum/Sniffs/JS/StrippingTagsSniff.php
  WordPressVIPMinimum/Sniffs/JS/WindowSniff.php
  WordPressVIPMinimum/Sniffs/Plugins/ZoninatorSniff.php
  WordPressVIPMinimum/Sniffs/TemplatingEngines/UnescapedOutputMustacheSniff.php
  WordPressVIPMinimum/Sniffs/TemplatingEngines/UnescapedOutputTwigSniff.php
  WordPressVIPMinimum/Sniffs/TemplatingEngines/UnescapedOutputUnderscorejsSniff.php
  WordPressVIPMinimum/Sniffs/TemplatingEngines/UnescapedOutputVuejsSniff.php
  WordPressVIPMinimum/Sniffs/VIP/EscapingVoidReturnFunctionsSniff.php
  WordPressVIPMinimum/Sniffs/VIP/ExitAfterRedirectSniff.php
  WordPressVIPMinimum/Sniffs/VIP/FetchingRemoteDataSniff.php
  WordPressVIPMinimum/Sniffs/VIP/MergeConflictSniff.php
  WordPressVIPMinimum/Sniffs/VIP/ProperEscapingFunctionSniff.php
  WordPressVIPMinimum/Sniffs/VIP/RobotstxtSniff.php
  WordPressVIPMinimum/Sniffs/VIP/StaticStrreplaceSniff.php
  WordPressVIPMinimum/Sniffs/VIP/TaxonomyMetaInOptionsSniff.php
  WordPressVIPMinimum/Sniffs/VIP/WPQueryParamsSniff.php
  WordPressVIPMinimum/Sniffs/Variables/ServerVariablesSniff.php
  WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisHelper.php
  WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisSniff.php
Labels: Type: Documentation

#343 Remove non-existing function: url_to_post_id
  WordPressVIPMinimum/Sniffs/VIP/RestrictedFunctionsSniff.php
Labels: Type: Bug

#346 Upgrade exec() and shell_exec() to be flagged as error
  WordPressVIPMinimum/ruleset.xml
Labels: Type: Enhancement

#350 Inspection: Remove unused items
  WordPressVIPMinimum/Sniffs/Classes/RestrictedExtendClassesSniff.php
  WordPressVIPMinimum/Sniffs/Functions/CheckReturnValueSniff.php
  WordPressVIPMinimum/Sniffs/JS/WindowSniff.php
  WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisSniff.php
Labels: Type: Maintenance

#351 Inspection: Fix undefined classes
  WordPressVIPMinimum/Sniffs/Functions/RestrictedFunctionsSniff.php
  WordPressVIPMinimum/Sniffs/UserExperience/AdminBarRemovalSniff.php
Labels: Type: Maintenance

#354 Inspection: Fix duplicate array keys
  WordPressVIPMinimum/Sniffs/JS/WindowSniff.php
  WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisSniff.php
  WordPressVIPMinimum/Tests/Classes/DeclarationCompatibilityUnitTest.php
Labels: Type: Maintenance

#355 Inspection: Remove redundant self-assignment
  WordPressVIPMinimum/Sniffs/Compatibility/ZoninatorSniff.php
Labels: Type: Maintenance

#353 Inspection: Fix assignment in condition
  WordPressVIPMinimum/Sniffs/Files/IncludingNonPHPFileSniff.php
  WordPressVIPMinimum/Sniffs/Hooks/AlwaysReturnInFilterSniff.php
  WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisSniff.php
Labels: Type: Maintenance

#356 Inspection: Remove returning void function calls
  WordPressVIPMinimum/Sniffs/UserExperience/AdminBarRemovalSniff.php
  WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisSniff.php
Labels: Type: Maintenance

#360 Tests: Fix Robotstxt test class name and file name
  WordPressVIPMinimum/Tests/Compatibility/RobotstxtUnitTest.inc
  WordPressVIPMinimum/Tests/Compatibility/RobotstxtUnitTest.php
Labels: Type: Maintenance

#361 Inspections: Multiple fixes
  WordPressVIPMinimum/Sniffs/AbstractVariableRestrictionsSniff.php
  WordPressVIPMinimum/Sniffs/Classes/DeclarationCompatibilitySniff.php
  WordPressVIPMinimum/Sniffs/Compatibility/ZoninatorSniff.php
  WordPressVIPMinimum/Sniffs/Constants/ConstantStringSniff.php
  WordPressVIPMinimum/Sniffs/Constants/RestrictedConstantsSniff.php
  WordPressVIPMinimum/Sniffs/Files/IncludingFileSniff.php
  WordPressVIPMinimum/Sniffs/Files/IncludingNonPHPFileSniff.php
  WordPressVIPMinimum/Sniffs/Functions/CheckReturnValueSniff.php
  WordPressVIPMinimum/Sniffs/Functions/RestrictedFunctionsSniff.php
  WordPressVIPMinimum/Sniffs/Hooks/AlwaysReturnInFilterSniff.php
  WordPressVIPMinimum/Sniffs/Hooks/PreGetPostsSniff.php
  WordPressVIPMinimum/Sniffs/JS/DangerouslySetInnerHTMLSniff.php
  WordPressVIPMinimum/Sniffs/JS/HTMLExecutingFunctionsSniff.php
  WordPressVIPMinimum/Sniffs/JS/InnerHTMLSniff.php
  WordPressVIPMinimum/Sniffs/JS/StringConcatSniff.php
  WordPressVIPMinimum/Sniffs/JS/StrippingTagsSniff.php
  WordPressVIPMinimum/Sniffs/JS/WindowSniff.php
  WordPressVIPMinimum/Sniffs/Performance/BatcacheWhitelistedParamsSniff.php
  WordPressVIPMinimum/Sniffs/Performance/CacheValueOverrideSniff.php
  WordPressVIPMinimum/Sniffs/Performance/FetchingRemoteDataSniff.php
  WordPressVIPMinimum/Sniffs/Performance/LowExpiryCacheTimeSniff.php
  WordPressVIPMinimum/Sniffs/Performance/OrderByRandSniff.php
  WordPressVIPMinimum/Sniffs/Performance/RegexpCompareSniff.php
  WordPressVIPMinimum/Sniffs/Performance/RemoteRequestTimeoutSniff.php
  WordPressVIPMinimum/Sniffs/Performance/TaxonomyMetaInOptionsSniff.php
  WordPressVIPMinimum/Sniffs/Performance/WPQueryParamsSniff.php
  WordPressVIPMinimum/Sniffs/Security/EscapingVoidReturnFunctionsSniff.php
  WordPressVIPMinimum/Sniffs/Security/ExitAfterRedirectSniff.php
  WordPressVIPMinimum/Sniffs/Security/MustacheSniff.php
  WordPressVIPMinimum/Sniffs/Security/PHPFilterFunctionsSniff.php
  WordPressVIPMinimum/Sniffs/Security/ProperEscapingFunctionSniff.php
  WordPressVIPMinimum/Sniffs/Security/StaticStrreplaceSniff.php
  WordPressVIPMinimum/Sniffs/Security/TwigSniff.php
  WordPressVIPMinimum/Sniffs/Security/UnderscorejsSniff.php
  WordPressVIPMinimum/Sniffs/Security/VuejsSniff.php
  WordPressVIPMinimum/Sniffs/UserExperience/AdminBarRemovalSniff.php
  WordPressVIPMinimum/Sniffs/Variables/ServerVariablesSniff.php
  WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisHelper.php
  WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisSniff.php
  WordPressVIPMinimum/Sniffs/VersionControl/MergeConflictSniff.php
  tests/bootstrap.php
Labels: Type: Maintenance
