Repository Automattic/VIP-Coding-Standards, pull requests merged in 2020-07, with the labels that each got.

#484 Dependencies: Update versions
  .travis.yml
  composer.json
Labels: Type: Maintenance

#437 HTMLExecutingFunctions: Add more functions
  WordPressVIPMinimum/Sniffs/JS/HTMLExecutingFunctionsSniff.php
  WordPressVIPMinimum/Tests/JS/HTMLExecutingFunctionsUnitTest.js
  WordPressVIPMinimum/Tests/JS/HTMLExecutingFunctionsUnitTest.php
Labels: Type: Enhancement

#455 Travis: test against PHP 7.4, not snapshot
  .travis.yml
Labels: Type: Maintenance

#490 Travis: Use PHPUnit 7 with PHP 8
  .travis.yml
Labels: Type: Maintenance

#487 Docs: Changelog for 2.1.0
  CHANGELOG.md
  README.md
Labels: Type: Documentation

#488 Release version 2.1.0
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/release-template.md
  .phpcs.xml.dist
  .travis.yml
  CHANGELOG.md
  README.md
  WordPress-VIP-Go/ruleset-test.inc
  WordPress-VIP-Go/ruleset-test.php
  WordPress-VIP-Go/ruleset.xml
  WordPressVIPMinimum/Sniffs/Files/IncludingFileSniff.php
  WordPressVIPMinimum/Sniffs/Functions/DynamicCallsSniff.php
  WordPressVIPMinimum/Sniffs/Functions/RestrictedFunctionsSniff.php
  WordPressVIPMinimum/Sniffs/JS/HTMLExecutingFunctionsSniff.php
  WordPressVIPMinimum/Sniffs/VersionControl/MergeConflictSniff.php
  WordPressVIPMinimum/Tests/Files/IncludingFileUnitTest.inc
  WordPressVIPMinimum/Tests/Files/IncludingFileUnitTest.php
  WordPressVIPMinimum/Tests/Functions/RestrictedFunctionsUnitTest.inc
  WordPressVIPMinimum/Tests/Functions/RestrictedFunctionsUnitTest.php
  WordPressVIPMinimum/Tests/JS/HTMLExecutingFunctionsUnitTest.js
  WordPressVIPMinimum/Tests/JS/HTMLExecutingFunctionsUnitTest.php
  WordPressVIPMinimum/Tests/VersionControl/MergeConflictUnitTest.inc
  WordPressVIPMinimum/Tests/VersionControl/MergeConflictUnitTest.php
  WordPressVIPMinimum/ruleset-test.inc
  WordPressVIPMinimum/ruleset-test.php
  WordPressVIPMinimum/ruleset.xml
  composer.json
Labels: Type: Maintenance

#450 Switch to sirbrillig/phpcs-variable-analysis
  WordPress-VIP-Go/ruleset-test.inc
  WordPress-VIP-Go/ruleset-test.php
  WordPress-VIP-Go/ruleset.xml
  WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisHelper.php
  WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisSniff.php
  WordPressVIPMinimum/Tests/Variables/VariableAnalysisUnitTest.inc
  WordPressVIPMinimum/Tests/Variables/VariableAnalysisUnitTest.php
  WordPressVIPMinimum/ruleset-test.inc
  WordPressVIPMinimum/ruleset-test.php
  WordPressVIPMinimum/ruleset.xml
  composer.json
Labels: Priority: High, Standard: VIP-Go, Standard: VIPMinimum, Type: Enhancement

#500 Travis: change from "trusty" to "xenial"
  .travis.yml
Labels: Type: Maintenance

#501 Contributing: improve the text
  .github/CONTRIBUTING.md
  README.md
Labels: Type: Documentation

#502 CS ruleset: minor tweaks
  .phpcs.xml.dist
Labels: Type: Maintenance

#503 RulesetTest: fix compatibility with Windows
  tests/RulesetTest.php
Labels: Type: Maintenance

#505 DeclarationCompatibility: fix incorrect signature check for `Walker::walk()`
  WordPressVIPMinimum/Sniffs/Classes/DeclarationCompatibilitySniff.php
  WordPressVIPMinimum/Tests/Classes/DeclarationCompatibilityUnitTest.inc
  WordPressVIPMinimum/Tests/Classes/DeclarationCompatibilityUnitTest.php
Labels: Type: Enhancement

#504 WordPressVIPMinimum: fix the failing ruleset test & let Travis show failures
  WordPressVIPMinimum/ruleset-test.inc
  bin/ruleset-tests
  tests/RulesetTest.php
Labels: Type: Maintenance

#508 RulesetTest: don't use the system default version of PHP
  tests/RulesetTest.php
Labels: Type: Maintenance

#509 Ruleset Tests: revert 485 and fix it
  WordPress-VIP-Go/ruleset-test.inc
  WordPress-VIP-Go/ruleset-test.php
  WordPressVIPMinimum/ruleset-test.inc
  WordPressVIPMinimum/ruleset-test.php
Labels: Type: Maintenance

#557 Contributing: remove duplicate info
  .github/CONTRIBUTING.md
Labels: Type: Documentation

#558 Test bootstrap: various minor tweaks
  tests/bootstrap.php
Labels: Type: Maintenance

#559 Variables/RestrictedVariables: fix namespace of unit test file + fix test
  WordPressVIPMinimum/Tests/Variables/RestrictedVariablesUnitTest.inc
  WordPressVIPMinimum/Tests/Variables/RestrictedVariablesUnitTest.php
Labels: Type: Maintenance

#561 Functions/RestrictedFunctions: fix false positive on class instantiation
  WordPressVIPMinimum/Sniffs/Functions/RestrictedFunctionsSniff.php
  WordPressVIPMinimum/Tests/Functions/RestrictedFunctionsUnitTest.inc
Labels: Type: Bug

#566 RestrictedFunctions: fix false negative - functions in `config_settings` would never match
  WordPress-VIP-Go/ruleset-test.inc
  WordPressVIPMinimum/Sniffs/Functions/RestrictedFunctionsSniff.php
  WordPressVIPMinimum/Tests/Functions/RestrictedFunctionsUnitTest.inc
  WordPressVIPMinimum/ruleset-test.inc
Labels: Type: Bug

#565 PreGetPosts: improve the isEarlyMainQueryCheck() method
  WordPressVIPMinimum/Sniffs/Hooks/PreGetPostsSniff.php
  WordPressVIPMinimum/Tests/Hooks/PreGetPostsUnitTest.inc
Labels: Type: Bug

#563 Hooks/AlwaysReturnInFilter: add support for hook-ins using short arrays
  WordPressVIPMinimum/Sniffs/Hooks/AlwaysReturnInFilterSniff.php
  WordPressVIPMinimum/Tests/Hooks/AlwaysReturnInFilterUnitTest.inc
  WordPressVIPMinimum/Tests/Hooks/AlwaysReturnInFilterUnitTest.php
Labels: Type: Bug

#564 Hooks/PreGetPosts: add support for hook-ins using short arrays
  WordPressVIPMinimum/Sniffs/Hooks/PreGetPostsSniff.php
  WordPressVIPMinimum/Tests/Hooks/PreGetPostsUnitTest.inc
  WordPressVIPMinimum/Tests/Hooks/PreGetPostsUnitTest.php
Labels: Type: Bug

#569 RestrictedVariables: don't report on "use" in `isset()`
  WordPress-VIP-Go/ruleset-test.inc
  WordPressVIPMinimum/Sniffs/AbstractVariableRestrictionsSniff.php
  WordPressVIPMinimum/Tests/Variables/RestrictedVariablesUnitTest.inc
  WordPressVIPMinimum/Tests/Variables/RestrictedVariablesUnitTest.php
Labels: Type: Enhancement

#571 CS: remove yoda conditions from VIPCS codebase
  .phpcs.xml.dist
  WordPressVIPMinimum/Sniffs/AbstractVariableRestrictionsSniff.php
  WordPressVIPMinimum/Sniffs/Classes/DeclarationCompatibilitySniff.php
  WordPressVIPMinimum/Sniffs/Classes/RestrictedExtendClassesSniff.php
  WordPressVIPMinimum/Sniffs/Compatibility/ZoninatorSniff.php
  WordPressVIPMinimum/Sniffs/Constants/ConstantStringSniff.php
  WordPressVIPMinimum/Sniffs/Constants/RestrictedConstantsSniff.php
  WordPressVIPMinimum/Sniffs/Files/IncludingFileSniff.php
  WordPressVIPMinimum/Sniffs/Files/IncludingNonPHPFileSniff.php
  WordPressVIPMinimum/Sniffs/Functions/CheckReturnValueSniff.php
  WordPressVIPMinimum/Sniffs/Functions/DynamicCallsSniff.php
  WordPressVIPMinimum/Sniffs/Functions/RestrictedFunctionsSniff.php
  WordPressVIPMinimum/Sniffs/Functions/StripTagsSniff.php
  WordPressVIPMinimum/Sniffs/Hooks/AlwaysReturnInFilterSniff.php
  WordPressVIPMinimum/Sniffs/Hooks/PreGetPostsSniff.php
  WordPressVIPMinimum/Sniffs/Hooks/RestrictedHooksSniff.php
  WordPressVIPMinimum/Sniffs/JS/DangerouslySetInnerHTMLSniff.php
  WordPressVIPMinimum/Sniffs/JS/HTMLExecutingFunctionsSniff.php
  WordPressVIPMinimum/Sniffs/JS/InnerHTMLSniff.php
  WordPressVIPMinimum/Sniffs/JS/StringConcatSniff.php
  WordPressVIPMinimum/Sniffs/JS/StrippingTagsSniff.php
  WordPressVIPMinimum/Sniffs/JS/WindowSniff.php
  WordPressVIPMinimum/Sniffs/Performance/BatcacheWhitelistedParamsSniff.php
  WordPressVIPMinimum/Sniffs/Performance/CacheValueOverrideSniff.php
  WordPressVIPMinimum/Sniffs/Performance/FetchingRemoteDataSniff.php
  WordPressVIPMinimum/Sniffs/Performance/LowExpiryCacheTimeSniff.php
  WordPressVIPMinimum/Sniffs/Performance/NoPagingSniff.php
  WordPressVIPMinimum/Sniffs/Performance/OrderByRandSniff.php
  WordPressVIPMinimum/Sniffs/Performance/RegexpCompareSniff.php
  WordPressVIPMinimum/Sniffs/Performance/TaxonomyMetaInOptionsSniff.php
  WordPressVIPMinimum/Sniffs/Performance/WPQueryParamsSniff.php
  WordPressVIPMinimum/Sniffs/Security/EscapingVoidReturnFunctionsSniff.php
  WordPressVIPMinimum/Sniffs/Security/ExitAfterRedirectSniff.php
  WordPressVIPMinimum/Sniffs/Security/MustacheSniff.php
  WordPressVIPMinimum/Sniffs/Security/PHPFilterFunctionsSniff.php
  WordPressVIPMinimum/Sniffs/Security/ProperEscapingFunctionSniff.php
  WordPressVIPMinimum/Sniffs/Security/StaticStrreplaceSniff.php
  WordPressVIPMinimum/Sniffs/Security/TwigSniff.php
  WordPressVIPMinimum/Sniffs/Security/UnderscorejsSniff.php
  WordPressVIPMinimum/Sniffs/Security/VuejsSniff.php
  WordPressVIPMinimum/Sniffs/UserExperience/AdminBarRemovalSniff.php
  WordPressVIPMinimum/Sniffs/Variables/ServerVariablesSniff.php
  WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisSniff.php
  tests/RulesetTest.php
  tests/bootstrap.php
Labels: Type: Maintenance
