Repository Automattic/VIP-Coding-Standards, pull requests merged in 2020-10, with the labels that each got.

#444 ConstantStringSniff: Take into account namespace prefixing
  WordPressVIPMinimum/Sniffs/Constants/ConstantStringSniff.php
  WordPressVIPMinimum/Tests/Constants/ConstantStringUnitTest.inc
Labels: Type: Bug

#587 LowExpiryCacheTime: add extra warning + lots of bug fixes
  WordPressVIPMinimum/Sniffs/Performance/LowExpiryCacheTimeSniff.php
  WordPressVIPMinimum/Tests/Performance/LowExpiryCacheTimeUnitTest.inc
  WordPressVIPMinimum/Tests/Performance/LowExpiryCacheTimeUnitTest.php
Labels: Standard: VIPMinimum, Type: Bug, Type: Enhancement

#589 WPQueryParams: sniff for `exclude` array key being set
  WordPressVIPMinimum/Sniffs/Performance/WPQueryParamsSniff.php
  WordPressVIPMinimum/Tests/Performance/WPQueryParamsUnitTest.inc
  WordPressVIPMinimum/Tests/Performance/WPQueryParamsUnitTest.php
Labels: Breaking Change, Type: Enhancement
