Repository Automattic/VIP-Coding-Standards, pull requests merged in 2020-09, with the labels that each got.

#579 Docs: Add comparisons and props for old versions
  CHANGELOG.md
Labels: Type: Maintenance

#577 Change log for VIPCS 2.2.0
  CHANGELOG.md
Labels: Type: Maintenance

#582 Travis: retry composer install on failure
  .travis.yml
Labels: Type: Maintenance

#584 Performance: more selective sniffing for efficiency
  WordPressVIPMinimum/Sniffs/Compatibility/ZoninatorSniff.php
  WordPressVIPMinimum/Sniffs/Functions/CheckReturnValueSniff.php
  WordPressVIPMinimum/Sniffs/Hooks/AlwaysReturnInFilterSniff.php
  WordPressVIPMinimum/Sniffs/Hooks/PreGetPostsSniff.php
  WordPressVIPMinimum/Sniffs/Performance/CacheValueOverrideSniff.php
  WordPressVIPMinimum/Sniffs/Performance/FetchingRemoteDataSniff.php
  WordPressVIPMinimum/Sniffs/Performance/TaxonomyMetaInOptionsSniff.php
  WordPressVIPMinimum/Sniffs/Security/ExitAfterRedirectSniff.php
  WordPressVIPMinimum/Sniffs/Security/ProperEscapingFunctionSniff.php
  WordPressVIPMinimum/Sniffs/Security/StaticStrreplaceSniff.php
Labels: Type: Bug

#583 Composer: require the DealerDirect plugin
  README.md
  composer.json
Labels: Type: Enhancement

#585 Hooks/AlwaysReturnInFilter: adjust expectations for a test
  WordPressVIPMinimum/Tests/Hooks/AlwaysReturnInFilterUnitTest.inc
  WordPressVIPMinimum/Tests/Hooks/AlwaysReturnInFilterUnitTest.php
Labels: Type: Maintenance

#586 Files/IncludingNonPHPFile: various improvements
  WordPressVIPMinimum/Sniffs/Files/IncludingNonPHPFileSniff.php
  WordPressVIPMinimum/Tests/Files/IncludingNonPHPFileUnitTest.inc
  WordPressVIPMinimum/Tests/Files/IncludingNonPHPFileUnitTest.php
Labels: Standard: VIPMinimum, Type: Bug, Type: Enhancement
