Repository Automattic/VIP-Coding-Standards, pull requests merged in 2020-08, with the labels that each got.

#560 Allow for checking test code coverage
  .gitignore
  WordPressVIPMinimum/Tests/Classes/DeclarationCompatibilityUnitTest.php
  WordPressVIPMinimum/Tests/Classes/RestrictedExtendClassesUnitTest.php
  WordPressVIPMinimum/Tests/Compatibility/ZoninatorUnitTest.php
  WordPressVIPMinimum/Tests/Constants/ConstantStringUnitTest.php
  WordPressVIPMinimum/Tests/Constants/RestrictedConstantsUnitTest.php
  WordPressVIPMinimum/Tests/Files/IncludingFileUnitTest.php
  WordPressVIPMinimum/Tests/Files/IncludingNonPHPFileUnitTest.php
  WordPressVIPMinimum/Tests/Functions/CheckReturnValueUnitTest.php
  WordPressVIPMinimum/Tests/Functions/DynamicCallsUnitTest.php
  WordPressVIPMinimum/Tests/Functions/RestrictedFunctionsUnitTest.php
  WordPressVIPMinimum/Tests/Functions/StripTagsUnitTest.php
  WordPressVIPMinimum/Tests/Hooks/AlwaysReturnInFilterUnitTest.php
  WordPressVIPMinimum/Tests/Hooks/PreGetPostsUnitTest.php
  WordPressVIPMinimum/Tests/Hooks/RestrictedHooksUnitTest.php
  WordPressVIPMinimum/Tests/JS/DangerouslySetInnerHTMLUnitTest.php
  WordPressVIPMinimum/Tests/JS/HTMLExecutingFunctionsUnitTest.php
  WordPressVIPMinimum/Tests/JS/InnerHTMLUnitTest.php
  WordPressVIPMinimum/Tests/JS/StringConcatUnitTest.php
  WordPressVIPMinimum/Tests/JS/StrippingTagsUnitTest.php
  WordPressVIPMinimum/Tests/JS/WindowUnitTest.php
  WordPressVIPMinimum/Tests/Performance/BatcacheWhitelistedParamsUnitTest.php
  WordPressVIPMinimum/Tests/Performance/CacheValueOverrideUnitTest.php
  WordPressVIPMinimum/Tests/Performance/FetchingRemoteDataUnitTest.php
  WordPressVIPMinimum/Tests/Performance/LowExpiryCacheTimeUnitTest.php
  WordPressVIPMinimum/Tests/Performance/NoPagingUnitTest.php
  WordPressVIPMinimum/Tests/Performance/OrderByRandUnitTest.php
  WordPressVIPMinimum/Tests/Performance/RegexpCompareUnitTest.php
  WordPressVIPMinimum/Tests/Performance/RemoteRequestTimeoutUnitTest.php
  WordPressVIPMinimum/Tests/Performance/TaxonomyMetaInOptionsUnitTest.php
  WordPressVIPMinimum/Tests/Performance/WPQueryParamsUnitTest.php
  WordPressVIPMinimum/Tests/Security/EscapingVoidReturnFunctionsUnitTest.php
  WordPressVIPMinimum/Tests/Security/ExitAfterRedirectUnitTest.php
  WordPressVIPMinimum/Tests/Security/MustacheUnitTest.php
  WordPressVIPMinimum/Tests/Security/PHPFilterFunctionsUnitTest.php
  WordPressVIPMinimum/Tests/Security/ProperEscapingFunctionUnitTest.php
  WordPressVIPMinimum/Tests/Security/StaticStrreplaceUnitTest.php
  WordPressVIPMinimum/Tests/Security/TwigUnitTest.php
  WordPressVIPMinimum/Tests/Security/UnderscorejsUnitTest.php
  WordPressVIPMinimum/Tests/Security/VuejsUnitTest.php
  WordPressVIPMinimum/Tests/UserExperience/AdminBarRemovalUnitTest.php
  WordPressVIPMinimum/Tests/Variables/RestrictedVariablesUnitTest.php
  WordPressVIPMinimum/Tests/Variables/ServerVariablesUnitTest.php
  WordPressVIPMinimum/Tests/Variables/VariableAnalysisUnitTest.php
  bin/unit-tests
  bin/unit-tests-coverage
  composer.json
  phpunit.xml.dist
Labels: Type: Maintenance

#573 Composer: Change minimum stability to stable
  composer.json
Labels: Type: Maintenance

#576 Docs: Update notes for releasing
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/release-template.md
  README.md
Labels: Type: Documentation

#575 ProperEscaping: Fix message for action attribute
  WordPressVIPMinimum/Sniffs/Security/ProperEscapingFunctionSniff.php
  WordPressVIPMinimum/Tests/Security/ProperEscapingFunctionUnitTest.inc
  WordPressVIPMinimum/Tests/Security/ProperEscapingFunctionUnitTest.php
Labels: Type: Bug
