Repository Automattic/VIP-Coding-Standards, pull requests merged in 2021-04, with the labels that each got.

#655 QA: remove redundant PHPCS ignore annotations
  WordPress-VIP-Go/ruleset-test.php
  WordPressVIPMinimum/ruleset-test.inc
  WordPressVIPMinimum/ruleset-test.php
  tests/RulesetTest.php
Labels: Type: Maintenance

#654 LowExpiryCacheTime: improve handling of potential parse errors in eval-ed code
  WordPressVIPMinimum/Sniffs/Performance/LowExpiryCacheTimeSniff.php
  WordPressVIPMinimum/Tests/Performance/LowExpiryCacheTimeUnitTest.php
Labels: Type: Bug

#653 GH Actions: switch over to parallel linting of PHP files
  .github/workflows/basics.yml
  .github/workflows/test.yml
  bin/php-lint
  composer.json
Labels: Type: Maintenance

#652 RestrictedFunctions/RestrictedVariables: remove usermeta related errors
  WordPress-VIP-Go/ruleset-test.inc
  WordPress-VIP-Go/ruleset.xml
  WordPressVIPMinimum/Sniffs/Functions/RestrictedFunctionsSniff.php
  WordPressVIPMinimum/Sniffs/Variables/RestrictedVariablesSniff.php
  WordPressVIPMinimum/Tests/Functions/RestrictedFunctionsUnitTest.inc
  WordPressVIPMinimum/Tests/Functions/RestrictedFunctionsUnitTest.php
  WordPressVIPMinimum/Tests/Variables/RestrictedVariablesUnitTest.inc
  WordPressVIPMinimum/Tests/Variables/RestrictedVariablesUnitTest.php
  WordPressVIPMinimum/ruleset-test.inc
  WordPressVIPMinimum/ruleset-test.php
Labels: Type: Maintenance

#656 GH Actions: always check that all sniffs are feature complete
  .github/workflows/basics.yml
  composer.json
Labels: Type: Maintenance

#657 GH Actions: add "quicktest" stage for non-PR/merge builds
  .github/workflows/quicktest.yml
  .github/workflows/test.yml
Labels: Type: Maintenance

#658 Release template: add checkbox for dependency check
  .github/ISSUE_TEMPLATE/release-template.md
Labels: Type: Documentation

#663 Changelog: minor tweak
  CHANGELOG.md
Labels: Type: Documentation

#664 Changelog: minor tweak
  CHANGELOG.md
Labels: Type: Documentation

#668 ProperEscapingFunction: fix overreach
  WordPressVIPMinimum/Sniffs/Security/ProperEscapingFunctionSniff.php
  WordPressVIPMinimum/Tests/Security/ProperEscapingFunctionUnitTest.inc
Labels: Type: Bug

#673 Docs: Add version compare for bugs to checklist
  .github/ISSUE_TEMPLATE/release-template.md
Labels: Type: Documentation

#670 ProperEscapingFunction: improve "action" match precision
  WordPressVIPMinimum/Sniffs/Security/ProperEscapingFunctionSniff.php
  WordPressVIPMinimum/Tests/Security/ProperEscapingFunctionUnitTest.inc
  WordPressVIPMinimum/Tests/Security/ProperEscapingFunctionUnitTest.php
Labels: Type: Bug

#675 ProperEscapingFunction: allow for comma's in first short open echo tag expression
  WordPressVIPMinimum/Sniffs/Security/ProperEscapingFunctionSniff.php
  WordPressVIPMinimum/Tests/Security/ProperEscapingFunctionUnitTest.inc
  WordPressVIPMinimum/Tests/Security/ProperEscapingFunctionUnitTest.php
Labels: Type: Bug

#676 Add changelog for 2.3.1 release
  CHANGELOG.md
Labels: Type: Documentation

#677 2.3.1 Release
  .github/ISSUE_TEMPLATE/release-template.md
  CHANGELOG.md
  WordPressVIPMinimum/Sniffs/Security/ProperEscapingFunctionSniff.php
  WordPressVIPMinimum/Tests/Security/ProperEscapingFunctionUnitTest.inc
  WordPressVIPMinimum/Tests/Security/ProperEscapingFunctionUnitTest.php
Labels: Type: Maintenance

#681 ProperEscapingFunction: further improve attribute matching
  WordPressVIPMinimum/Sniffs/Security/ProperEscapingFunctionSniff.php
  WordPressVIPMinimum/Tests/Security/ProperEscapingFunctionUnitTest.inc
Labels: Type: Bug

#682 2.3.2 Changelog
  CHANGELOG.md
Labels: Type: Documentation

#683 Release 2.3.2
  CHANGELOG.md
  WordPressVIPMinimum/Sniffs/Security/ProperEscapingFunctionSniff.php
  WordPressVIPMinimum/Tests/Security/ProperEscapingFunctionUnitTest.inc
Labels: Type: Maintenance
