Repository Automattic/VIP-Coding-Standards, pull requests merged in 2023-08, with the labels that each got.

#759 Bug report template: make version table more comprehensive
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Type: Maintenance

#761 Performance/RegexpCompare: remove redundant condition
  WordPressVIPMinimum/Sniffs/Performance/RegexpCompareSniff.php
Labels: Type: Maintenance

#765 Rulesets: fix the `name`s
  WordPress-VIP-Go/ruleset.xml
  WordPressVIPMinimum/ruleset.xml
Labels: Type: Maintenance

#767 GH Actions: 2 minor simplification
  .github/workflows/basics.yml
  .github/workflows/quicktest.yml
  .github/workflows/test.yml
Labels: Type: Maintenance

#766 Various minor doc fixes
  WordPressVIPMinimum/Sniffs/Files/IncludingFileSniff.php
  WordPressVIPMinimum/Sniffs/Performance/BatcacheWhitelistedParamsSniff.php
  WordPressVIPMinimum/Sniffs/Performance/CacheValueOverrideSniff.php
  WordPressVIPMinimum/Sniffs/Performance/FetchingRemoteDataSniff.php
  WordPressVIPMinimum/Sniffs/Performance/RemoteRequestTimeoutSniff.php
  WordPressVIPMinimum/Tests/Files/IncludingFileUnitTest.inc
Labels: Type: Documentation

#763 Rulesets: move VariableAnalysis configuration from Go to Minimum
  WordPress-VIP-Go/ruleset.xml
  WordPressVIPMinimum/ruleset.xml
Labels: Type: Enhancement

#768 Classes/DeclarationCompatibility: remove redundant code
  WordPressVIPMinimum/Sniffs/Classes/DeclarationCompatibilitySniff.php
Labels: Type: Bug

#771 QA: fix condition order
  tests/RulesetTest.php
Labels: Type: Maintenance

#770 Docs: various @var/@param/@return tag improvements
  WordPressVIPMinimum/Sniffs/Classes/DeclarationCompatibilitySniff.php
  WordPressVIPMinimum/Sniffs/Classes/RestrictedExtendClassesSniff.php
  WordPressVIPMinimum/Sniffs/Functions/CheckReturnValueSniff.php
  WordPressVIPMinimum/Sniffs/Functions/StripTagsSniff.php
  WordPressVIPMinimum/Sniffs/Hooks/AlwaysReturnInFilterSniff.php
  WordPressVIPMinimum/Sniffs/Hooks/PreGetPostsSniff.php
  WordPressVIPMinimum/Sniffs/Hooks/RestrictedHooksSniff.php
  WordPressVIPMinimum/Sniffs/JS/StringConcatSniff.php
  WordPressVIPMinimum/Sniffs/Performance/CacheValueOverrideSniff.php
  WordPressVIPMinimum/Sniffs/Performance/LowExpiryCacheTimeSniff.php
  WordPressVIPMinimum/Sniffs/Security/PHPFilterFunctionsSniff.php
  WordPressVIPMinimum/Sniffs/UserExperience/AdminBarRemovalSniff.php
  WordPressVIPMinimum/Tests/Classes/DeclarationCompatibilityUnitTest.php
  WordPressVIPMinimum/Tests/Classes/RestrictedExtendClassesUnitTest.php
  WordPressVIPMinimum/Tests/Constants/ConstantStringUnitTest.php
  WordPressVIPMinimum/Tests/Constants/RestrictedConstantsUnitTest.php
  WordPressVIPMinimum/Tests/Files/IncludingFileUnitTest.php
  WordPressVIPMinimum/Tests/Files/IncludingNonPHPFileUnitTest.php
  WordPressVIPMinimum/Tests/Functions/CheckReturnValueUnitTest.php
  WordPressVIPMinimum/Tests/Functions/DynamicCallsUnitTest.php
  WordPressVIPMinimum/Tests/Functions/RestrictedFunctionsUnitTest.php
  WordPressVIPMinimum/Tests/Functions/StripTagsUnitTest.php
  WordPressVIPMinimum/Tests/Hooks/AlwaysReturnInFilterUnitTest.php
  WordPressVIPMinimum/Tests/Hooks/PreGetPostsUnitTest.php
  WordPressVIPMinimum/Tests/Hooks/RestrictedHooksUnitTest.php
  WordPressVIPMinimum/Tests/JS/DangerouslySetInnerHTMLUnitTest.php
  WordPressVIPMinimum/Tests/JS/HTMLExecutingFunctionsUnitTest.php
  WordPressVIPMinimum/Tests/JS/InnerHTMLUnitTest.php
  WordPressVIPMinimum/Tests/JS/StringConcatUnitTest.php
  WordPressVIPMinimum/Tests/JS/StrippingTagsUnitTest.php
  WordPressVIPMinimum/Tests/JS/WindowUnitTest.php
  WordPressVIPMinimum/Tests/Performance/CacheValueOverrideUnitTest.php
  WordPressVIPMinimum/Tests/Performance/FetchingRemoteDataUnitTest.php
  WordPressVIPMinimum/Tests/Performance/LowExpiryCacheTimeUnitTest.php
  WordPressVIPMinimum/Tests/Performance/NoPagingUnitTest.php
  WordPressVIPMinimum/Tests/Performance/OrderByRandUnitTest.php
  WordPressVIPMinimum/Tests/Performance/RegexpCompareUnitTest.php
  WordPressVIPMinimum/Tests/Performance/RemoteRequestTimeoutUnitTest.php
  WordPressVIPMinimum/Tests/Performance/TaxonomyMetaInOptionsUnitTest.php
  WordPressVIPMinimum/Tests/Performance/WPQueryParamsUnitTest.php
  WordPressVIPMinimum/Tests/Security/EscapingVoidReturnFunctionsUnitTest.php
  WordPressVIPMinimum/Tests/Security/ExitAfterRedirectUnitTest.php
  WordPressVIPMinimum/Tests/Security/MustacheUnitTest.php
  WordPressVIPMinimum/Tests/Security/PHPFilterFunctionsUnitTest.php
  WordPressVIPMinimum/Tests/Security/ProperEscapingFunctionUnitTest.php
  WordPressVIPMinimum/Tests/Security/StaticStrreplaceUnitTest.php
  WordPressVIPMinimum/Tests/Security/TwigUnitTest.php
  WordPressVIPMinimum/Tests/Security/UnderscorejsUnitTest.php
  WordPressVIPMinimum/Tests/Security/VuejsUnitTest.php
  WordPressVIPMinimum/Tests/UserExperience/AdminBarRemovalUnitTest.php
  WordPressVIPMinimum/Tests/Variables/RestrictedVariablesUnitTest.php
  WordPressVIPMinimum/Tests/Variables/ServerVariablesUnitTest.php
  tests/RulesetTest.php
Labels: Type: Documentation

#769 .gitattributes: minor readability improvement
  .gitattributes
Labels: Type: Maintenance

#775 Compatibility/Zoninator: remove the sniff
  WordPress-VIP-Go/ruleset-test.inc
  WordPress-VIP-Go/ruleset-test.php
  WordPressVIPMinimum/Sniffs/Compatibility/ZoninatorSniff.php
  WordPressVIPMinimum/Tests/Compatibility/ZoninatorUnitTest.inc
  WordPressVIPMinimum/Tests/Compatibility/ZoninatorUnitTest.php
  WordPressVIPMinimum/ruleset-test.inc
  WordPressVIPMinimum/ruleset-test.php
Labels: Type: Maintenance, Breaking Change

#777 3.0: start using PHPCSUtils
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
  WordPressVIPMinimum/Sniffs/AbstractVariableRestrictionsSniff.php
  WordPressVIPMinimum/Sniffs/Classes/DeclarationCompatibilitySniff.php
  WordPressVIPMinimum/Sniffs/Constants/ConstantStringSniff.php
  WordPressVIPMinimum/Sniffs/Files/IncludingNonPHPFileSniff.php
  WordPressVIPMinimum/Sniffs/Functions/DynamicCallsSniff.php
  WordPressVIPMinimum/Sniffs/Hooks/AlwaysReturnInFilterSniff.php
  WordPressVIPMinimum/Sniffs/Hooks/PreGetPostsSniff.php
  WordPressVIPMinimum/Sniffs/Performance/LowExpiryCacheTimeSniff.php
  WordPressVIPMinimum/Sniffs/Security/ProperEscapingFunctionSniff.php
  WordPressVIPMinimum/Sniffs/Security/UnderscorejsSniff.php
  WordPressVIPMinimum/Sniffs/UserExperience/AdminBarRemovalSniff.php
  WordPressVIPMinimum/ruleset.xml
  composer.json
  tests/bootstrap.php
Labels: Type: Enhancement, PHPCSUtils

#774 Performance/BatcacheWhitelistedParams: remove the sniff
  WordPress-VIP-Go/ruleset-test.inc
  WordPress-VIP-Go/ruleset-test.php
  WordPress-VIP-Go/ruleset.xml
  WordPressVIPMinimum/Sniffs/Performance/BatcacheWhitelistedParamsSniff.php
  WordPressVIPMinimum/Tests/Performance/BatcacheWhitelistedParamsUnitTest.inc
  WordPressVIPMinimum/Tests/Performance/BatcacheWhitelistedParamsUnitTest.php
  WordPressVIPMinimum/ruleset-test.inc
  WordPressVIPMinimum/ruleset-test.php
Labels: Type: Maintenance, Breaking Change

#778 CS: improve use statements
  WordPressVIPMinimum/Sniffs/Constants/RestrictedConstantsSniff.php
  WordPressVIPMinimum/Sniffs/Files/IncludingFileSniff.php
  WordPressVIPMinimum/Sniffs/Files/IncludingNonPHPFileSniff.php
  WordPressVIPMinimum/Sniffs/Functions/CheckReturnValueSniff.php
  WordPressVIPMinimum/Sniffs/Functions/RestrictedFunctionsSniff.php
  WordPressVIPMinimum/Sniffs/JS/DangerouslySetInnerHTMLSniff.php
  WordPressVIPMinimum/Sniffs/JS/HTMLExecutingFunctionsSniff.php
  WordPressVIPMinimum/Sniffs/JS/InnerHTMLSniff.php
  WordPressVIPMinimum/Sniffs/JS/StringConcatSniff.php
  WordPressVIPMinimum/Sniffs/JS/StrippingTagsSniff.php
  WordPressVIPMinimum/Sniffs/JS/WindowSniff.php
  WordPressVIPMinimum/Sniffs/Performance/CacheValueOverrideSniff.php
  WordPressVIPMinimum/Sniffs/Performance/FetchingRemoteDataSniff.php
  WordPressVIPMinimum/Sniffs/Performance/TaxonomyMetaInOptionsSniff.php
  WordPressVIPMinimum/Sniffs/Performance/WPQueryParamsSniff.php
  WordPressVIPMinimum/Sniffs/Security/EscapingVoidReturnFunctionsSniff.php
  WordPressVIPMinimum/Sniffs/Security/ExitAfterRedirectSniff.php
  WordPressVIPMinimum/Sniffs/Security/StaticStrreplaceSniff.php
  WordPressVIPMinimum/Sniffs/Sniff.php
  WordPressVIPMinimum/Sniffs/UserExperience/AdminBarRemovalSniff.php
Labels: Type: Maintenance

#779 3.0: support WordPressCS 3.0
  .github/workflows/basics.yml
  .github/workflows/quicktest.yml
  .github/workflows/test.yml
  .phpcs.xml.dist
  README.md
  WordPress-VIP-Go/ruleset-test.inc
  WordPress-VIP-Go/ruleset-test.php
  WordPress-VIP-Go/ruleset.xml
  WordPressVIPMinimum/Sniffs/AbstractVariableRestrictionsSniff.php
  WordPressVIPMinimum/Sniffs/Performance/NoPagingSniff.php
  WordPressVIPMinimum/Sniffs/Performance/OrderByRandSniff.php
  WordPressVIPMinimum/Sniffs/Performance/RegexpCompareSniff.php
  WordPressVIPMinimum/Sniffs/Security/EscapingVoidReturnFunctionsSniff.php
  WordPressVIPMinimum/ruleset-test.inc
  WordPressVIPMinimum/ruleset-test.php
  WordPressVIPMinimum/ruleset.xml
  composer.json
  tests/RulesetTest.php
Labels: Require: WPCS 3.0+, Require: VIPCS 3.0, Breaking Change

#780 Performance/WPQueryParams: defer to the parent sniff
  WordPressVIPMinimum/Sniffs/Performance/WPQueryParamsSniff.php
Labels: Type: Maintenance, Breaking Change

#781 Performance/NoPaging: add extra tests
  WordPressVIPMinimum/Tests/Performance/NoPagingUnitTest.inc
  WordPressVIPMinimum/Tests/Performance/NoPagingUnitTest.php
Labels: Type: Maintenance

#782 GH Actions: minor tweaks to the composer options used
  .github/workflows/quicktest.yml
  .github/workflows/test.yml
Labels: Type: Maintenance

#783 Hooks/AlwaysReturnInFilter: remove redundant condition
  WordPressVIPMinimum/Sniffs/Hooks/AlwaysReturnInFilterSniff.php
Labels: Type: Maintenance

#784 Performance/WPQueryParams: prevent false positives for 'exclude' with get_users()
  WordPressVIPMinimum/Sniffs/Performance/WPQueryParamsSniff.php
  WordPressVIPMinimum/Tests/Performance/WPQueryParamsUnitTest.inc
  WordPressVIPMinimum/Tests/Performance/WPQueryParamsUnitTest.php
Labels: Type: Bug

#786 Add PHPStan to QA checks
  .gitattributes
  .github/workflows/basics.yml
  .gitignore
  phpstan.neon.dist
Labels: Type: Maintenance

#787 GH Actions: tweak the way the PHPCS/WPCS versions are set
  .github/workflows/quicktest.yml
  .github/workflows/test.yml
Labels: Type: Maintenance

#788 Security/Mustache: prevent false positives on block editor templates
  WordPressVIPMinimum/Sniffs/Security/MustacheSniff.php
  WordPressVIPMinimum/Tests/Security/MustacheUnitTest.inc
Labels: Type: Bug

#789 Updates related to branch rename from master to main
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/release-template.md
  .github/workflows/quicktest.yml
  .github/workflows/test.yml
Labels: Type: Maintenance, Type: Documentation

#791 Docs: Update CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: Type: Documentation

#790 PHPUnit: Use 7.5 schema
  .github/CONTRIBUTING.md
  phpunit.xml.dist
Labels: Type: Maintenance
