Repository Automattic/VIP-Coding-Standards, pull requests merged in 2024-02, with the labels that each got.

#805 Switch to PHPCSStandards/PHP_CodeSniffer & raise minimum supported version
  .github/CONTRIBUTING.md
  .phpcs.xml.dist
  LICENSE.md
  README.md
  WordPress-VIP-Go/ruleset.xml
  WordPressVIPMinimum/ruleset.xml
  composer.json
Labels: Type: Maintenance

#809 Tests: allow for PHPUnit 8/9
  .github/CONTRIBUTING.md
  .github/workflows/basics.yml
  .github/workflows/quicktest.yml
  .github/workflows/test.yml
  .gitignore
  bin/unit-tests
  composer.json
  phpstan.neon.dist
  phpunit.xml.dist
Labels: Type: Maintenance

#810 CONTRIBUTING: minor tweak
  .github/CONTRIBUTING.md
Labels: Type: Documentation

#811 Docs: Fix links
  README.md
Labels: Type: Documentation

#812 End restricting usage of term_exists()
  WordPress-VIP-Go/ruleset-test.inc
  WordPress-VIP-Go/ruleset-test.php
  WordPressVIPMinimum/Sniffs/Functions/RestrictedFunctionsSniff.php
  WordPressVIPMinimum/Tests/Functions/RestrictedFunctionsUnitTest.inc
  WordPressVIPMinimum/Tests/Functions/RestrictedFunctionsUnitTest.php
  WordPressVIPMinimum/ruleset-test.inc
  WordPressVIPMinimum/ruleset-test.php
Labels: Type: Bug

#813 Docs: Fix changelog heading
  CHANGELOG.md
Labels: Type: Documentation

#814 End restricting usage of get_page_by_title()
  WordPress-VIP-Go/ruleset-test.inc
  WordPress-VIP-Go/ruleset-test.php
  WordPress-VIP-Go/ruleset.xml
  WordPressVIPMinimum/Sniffs/Functions/RestrictedFunctionsSniff.php
  WordPressVIPMinimum/Tests/Functions/RestrictedFunctionsUnitTest.inc
  WordPressVIPMinimum/Tests/Functions/RestrictedFunctionsUnitTest.php
  WordPressVIPMinimum/ruleset-test.inc
  WordPressVIPMinimum/ruleset-test.php
Labels: Type: Bug
